describe('Busqueda_y_eliminacion_de_un_member', () => {
  beforeEach(()=>{
    cy.visit('http://54.188.89.84/ghost/')
    cy.wait(5000)
    
 })
 it('Login', ()=>{
  cy.get('#identification').type('user@example.com')
  cy.wait(2000)
  cy.get('#password').type('123456789**')
  cy.wait(2000)
  cy.get('#ember5').click()
  cy.wait(2000)
  cy.get('a[data-test-nav=members]').click()
  cy.wait(2000)
  cy.get('a[data-test-new-member-button=true]').click()
  cy.wait(2000)
  cy.get('#member-name').type('Busqueda cypress 1')
  cy.wait(2000)
  cy.get('#member-email').type('Bcypress1@gmail.com')
  cy.wait(2000)
  cy.get('button[data-test-button=save]').click()
  cy.wait(2000)
  cy.get('a[data-test-nav=members]').click()
  cy.wait(2000)
  cy.get('a[data-test-new-member-button=true]').click()
  cy.wait(2000)
  cy.get('#member-name').type('Busqueda cypress 2')
  cy.wait(2000)
  cy.get('#member-email').type('Bcypress2@gmail.com')
  cy.wait(2000)
  cy.get('button[data-test-button=save]').click()
  cy.wait(2000)
  cy.get('a[data-test-nav=members]').click()
  cy.wait(2000)
  cy.get('input[data-test-input=members-search]').type('Busqueda cypress')
  cy.wait(2000)
  cy.get('tbody:nth-child(2)').click()
  cy.wait(2000)
  cy.get('button[data-test-button=member-actions]').click()
  cy.wait(2000)
  cy.get('button[data-test-button=delete-member]').click()
  cy.wait(2000)
  cy.get('button[data-test-button=confirm]').click()
  cy.wait(2000)
  cy.get('a[data-test-nav=dashboard]').click()
  cy.wait(2000)
  cy.get('a[data-test-nav=members]').click()
  cy.wait(2000)
  cy.contains('Bcypress1@gmail.com').should('not.exist')
  cy.wait(2000)
})
})